services:
  grassrootsbbs:
    build: .
    # Nginx経由でアクセスするため、直接ポートを公開する必要はなくなります
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs # アプリケーションログを永続化
      - ./src:/home/yuki/python/GrassRootsBBS/src # 開発用にソースコードをマウント
    ports:
      - "8183:5000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - SOCKETIO_ALLOWED_ORIGINS=http://localhost:8183
      - DB_HOST=mariadb
      - DB_NAME=grbbs
      - DB_USER=grbbs_user

    env_file:
      - .env # .env 必ず先に管理者IDとパスワードを設定してください。
    depends_on:
      - mariadb
      - redis # grassrootsbbs の前に redis を起動
    restart: unless-stopped

  mariadb:
    image: mariadb:10.6 # 特定のバージョンを指定することを推奨
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password # ここも変更
      - MYSQL_DATABASE=grbbs
      - MYSQL_USER=grbbs_user
      - MYSQL_PASSWORD=your_strong_password # webappのDB_PASSWORDと同じにする
    volumes:
      - mariadb_data:/var/lib/mysql
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10

  redis:
    image: "redis:alpine"
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:
