# ./config.toml

title = "BicliModel Configuration"

[security]
PBKDF2_ROUNDS = 100000                            # パスワードハッシュのストレチッング数
GUEST_ID_SALT = "korekaranonagaitatakiwosonaeeyo" # 必ずランダムで複雑な文字列に変更してください
ID_MIN_LENGTH = 3                                 #IDの最小文字数
ID_MAX_LENGTH = 20                                #IDの最大文字数
PASSWORD_MIN_LENGTH = 8                           #パスワードの最小文字数
PASSWORD_MAX_LENGTH = 64                          #パスワードの最大文字数
MAX_PASSWORD_ATTEMPTS = 3                         # パスワード最大試行回数
LOCKOUT_TIME_SECONDS = 300                        # アカウントロック時間（秒）

[limits]
mail_subject_max_length = 42                           #メールタイトルの最大文字数
mail_body_max_length = 8192                            #メール本文の最大文字数
bbs_title_max_length = 42                              #掲示板タイトルの最大文字数
bbs_body_max_length = 8192                             #掲示板本文の最大文字数
telegram_message_max_length = 42                       #電報の最大文字数
attachment_max_size_mb = 10                            # 添付ファイルの最大サイズ (MB)
allowed_attachment_extensions = "jpg,jpeg,png,gif,txt" # 許可する拡張子 (カンマ区切り)

[webapp]
# WEBAPP_KEY_PATH removed from here
WEBAPP_BIND_PORT = 50000
MAX_CONCURRENT_WEBAPP_CLIENTS = 4 # WebAppの同時接続可能クライアント数(0で無制限)
WEBAPP_USER = 'user' # WebAppのデフォルトユーザー名 (本番環境では変更を推奨)
WEBAPP_PASSWORD = 'pass' # WebAppのデフォルトパスワード (本番環境では変更を強く推奨)
LOGIN_PAGE_TITLE = "GR-BBS Login"
LOGIN_PAGE_LOGO_PATH = "images/logo.png" # static/からの相対パス
LOGIN_PAGE_MESSAGE = """Welcome to the Grass-Roots BBS.
Please enter your ID and PASSWORD.
guestID = `GUEST/GUEST`
"""

[push]
VAPID_PRIVATE_KEY = """-----BEGIN PRIVATE KEY-----
MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgDKStVK5Dp26dVBne
q1RiwGXyc+BZuhw31P3Tzc2uBomhRANCAASY0ltQ0a2lQeqIGO4dEQ0t2/JZ+DVc
OQOgCjDs+l2FYrvhyqDXUAv+edsZviGsEqSRPv8ZG/nmMfWjnDybyOsp
-----END PRIVATE KEY-----
"""
VAPID_CLAIMS_EMAIL = "mailto:your-email@example.com" # あなたのメールアドレスに変更
NOTIFICATION_COOLDOWN_SECONDS = 60 # 同じルームへの入室通知のクールダウン時間（秒）

[paths]
db_name = "data/bbs.db"                   # DBファイル名
log_dir = "logs"                          # ログファイルの保存先
text_data_yaml = "setting/textdata.yaml"  # BBS内で使われる定型文データ
bbs_mode1_yaml = "setting/bbs_mode1.yaml" # mode1での掲示板の階層設定ファイル
bbs_mode3_yaml = "setting/bbs_mode3.yaml" # mode2,3での掲示板の階層設定ファイル
chatroom_yaml = "setting/chatroom.yaml"   # チャットルームの階層設定ファイル
